### ISSUE TITLE
Color Picker content not centered

### ISSUE THREAD

**Issue by nkolba** [nkolba/electron-fdc3#15]
There is an uneven amount of whitespace around the color channel squares - resulting in the picker looking a bit off.  Spacing should be even all around.  Looks like the amount of spacing on the top and left is correct.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/1150874/161272855-99b8991f-516a-421c-afda-41c423d99638.png">

**Comment by Ngoakor12** [comment]
Hey, I really wanted to help with these color picker issues. I can't seem to be able to run the app locally. I get this error when running `npm run start:directory command`: 
![image](https://user-images.githubusercontent.com/54069197/161363215-948ecfde-d827-4d82-a5e2-b71339a4571c.png)

I'm not familiar with type script and electron but I know my way around css and I'm sure I could help If I could get the app to run for previews

**Comment by nkolba** [comment]
Hey, thanks for looking at the project and jumping in to help with issues!  

The directory is just a local node server.  Looks like the problem is that you already have something running on the localhost port the directory uses by default (8080).  The simplest solution would be to shut down what you already have running on 8080, otherwise, it is relatively simple to change the local directory port.   The port is defined in `/directory/config.ts`.

**Comment by Ngoakor12** [comment]
Hey, I managed to get over that and a bunch of more errors but still can't get it working.

After starting the app with `npm start` and going to `localhost:port` I get a 404. See screenshoot: 
![image](https://user-images.githubusercontent.com/54069197/161392099-6eea8e8b-7d7f-4d1c-873b-fb922f83134b.png)

Any ideas what could be wrong?

**Comment by nkolba** [comment]
Looks like I'm missing a default response for the directory.  Can you try navigating to `localhost:8003/apps` ?  You should get a JSON response that should look like the below:

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/1150874/161392613-162512f6-f00a-44f2-a24b-3d37d93373dc.png">

**Comment by Ngoakor12** [comment]
I can. but I was hoping you could help me get a view of some sort so that I can be able to see how my changes reflect in the UI(like the first screenshot of the issue) not a JSON response.

**Comment by nkolba** [comment]
The directory only provides data to the UI.  The UI lives entirely in the Electron part of the project.  To see that, run `npm start` this will run the electron app.

**Comment by Ngoakor12** [comment]
That command runs without errors, but no app launches:
![image](https://user-images.githubusercontent.com/54069197/161394015-0b6531b3-d064-4293-9bd0-12c9cd4ba1e3.png)

**Comment by nkolba** [comment]
just tested with a clean set up.  

- clone the repo and `cd electron-fdc3`
- `npm i`
- `npm run build:directory`
- `npm run start:directory`
- in a new terminal, 
- `cd electron-fdc3`
- `npm start`

You should see this launch:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/1150874/161397759-355b2509-7674-4013-ad2a-417fe7b0db9e.png">


Note, it is a standalone electron app, not in a browser.

If you have not worked with electron before, it may be useful to first try a more simple 'hello world' for electron.  As this project is a bit more complicated than the average electron app.

**Comment by Ngoakor12** [comment]
Hey, I couldn't get it to work, but thanks for trying to help.

I even tried to launch the quick-start electron project from the electron website and kept getting nowhere. I think it has something to do with my machine, I tried it on my current wsl setup and my windows setup with no luck.

**Comment by nkolba** [comment]
Understood.  Some of these things are non-obvious.  The upside is that you identified a different issue (no response from the app directory on the ‘/‘ route)!  Feel free to come back to this anytime .

**Comment by nkolba** [comment]
fixed
